---
# tasks file for system-profile
- name: Add test block to /etc/profile
  lineinfile:
    path: /etc/profile
    line: '# Amandeep Kaur'
    insertafter: EOF
    create: yes

- name: Set TMOUT environment variable in /etc/profile
  lineinfile:
    path: /etc/profile
    line: 'export TMOUT=1800'
    insertafter: EOF
